
services:

  db:
    image: postgres:15-alpine
    container_name: ${CONTAINER_NAME_TEMPLATE:-infodesk}_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-infodesk}
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    container_name: ${CONTAINER_NAME_TEMPLATE:-infodesk}_web
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  redis:
    image: redis:7
    restart: unless-stopped
    container_name: ${CONTAINER_NAME_TEMPLATE:-infodesk}_redis

  worker:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    container_name: ${CONTAINER_NAME_TEMPLATE:-infodesk}_worker
    environment:
      DJANGO_ENV: dev
    command: celery -A config worker -l info
    entrypoint: []
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - redis

  beat:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    container_name: ${CONTAINER_NAME_TEMPLATE:-infodesk}_beat
    environment:
      DJANGO_ENV: dev
    command: celery -A config beat -l info
    entrypoint: []
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  postgres_data:
  media:
  static:
