
services:

  db:
    image: postgres:15-alpine
    container_name: ${CONTAINER_NAME_TEMPLATE}_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    container_name: ${CONTAINER_NAME_TEMPLATE}_web
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - redis

  redis:
    image: redis:7
    restart: unless-stopped
    container_name: ${CONTAINER_NAME_TEMPLATE}_redis

  worker:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    container_name: ${CONTAINER_NAME_TEMPLATE}_worker
    environment:
      DJANGO_ENV: dev
    command: celery -A config worker -l info
    entrypoint: []
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - redis

  beat:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    container_name: ${CONTAINER_NAME_TEMPLATE}_beat
    environment:
      DJANGO_ENV: dev
    command: celery -A config beat -l info
    entrypoint: []
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  postgres_data:
  media:
  static:
