# Generated by Django 6.0.2 on 2026-02-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
