# Generated by Django 5.2.11 on 2026-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('admin', 'Administrator'), ('meneger', 'Menejer'), ('ceo', 'Direktor'), ('teacher', "O'qituvchi"), ('student', "O'quvchi")], default='user', max_length=30),
        ),
    ]
