# Generated by Django 5.2.11 on 2026-03-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='bonus_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operator',
            name='penalty_point',
            field=models.IntegerField(default=0),
        ),
    ]
