# Generated by Django 5.2.11 on 2026-03-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('meneger', 'Meneger'), ('ceo', 'Ceo'), ('student', 'Student')], default='user', max_length=30),
        ),
    ]
