# Generated by Django 6.0.2 on 2026-02-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_choice', models.CharField(blank=True, choices=[('odd days', 'Odd days'), ('even days', 'Even days')], max_length=30, null=True)),
                ('status', models.CharField(choices=[('new', 'New')], default='new', max_length=25)),
                ('source', models.CharField(choices=[('telegram', 'Telergam'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'Whatsapp'), ('other', 'Other')], max_length=30)),
                ('temperature', models.CharField(choices=[('hot', 'Hot'), ('cool', 'Cool'), ('worm', 'Worm')], default='hot', max_length=20)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_static', models.BooleanField(default=False)),
            ],
        ),
    ]
