# Generated by Django 5.2.11 on 2026-02-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('days_choice', models.CharField(blank=True, choices=[('odd days', 'Odd days'), ('even days', 'Even days')], max_length=30, null=True)),
                ('prefer_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New')], default='new', max_length=25)),
                ('temperature', models.CharField(choices=[('hot', 'Hot'), ('cool', 'Cool'), ('worm', 'Worm')], default='hot', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_static', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='sourse-icon')),
                ('is_static', models.BooleanField(default=False)),
            ],
        ),
    ]
