# Generated by Django 5.2.11 on 2026-03-24 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0003_initial'),
        ('lead', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='settings.organization'),
        ),
        migrations.AddField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='group.coursetemplate'),
        ),
        migrations.AddField(
            model_name='lead',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='leads', to='group.day'),
        ),
        migrations.AddField(
            model_name='lead',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group'),
        ),
    ]
