# Generated by Django 5.2.11 on 2026-02-28 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0002_initial'),
        ('settings', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='user.operator'),
        ),
        migrations.AddField(
            model_name='note',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.lead'),
        ),
        migrations.AddField(
            model_name='note',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.operator'),
        ),
        migrations.AddField(
            model_name='situation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.organization'),
        ),
        migrations.AddField(
            model_name='lead',
            name='situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.situation'),
        ),
        migrations.AddField(
            model_name='source',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.organization'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='lead.source'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['center', 'status'], name='lead_center_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['center', '-created_at'], name='lead_center_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['operator', 'status'], name='lead_operator_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['course'], name='lead_course_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone_number'], name='lead_phone_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', True), ('is_archived', True), _negated=True), name='prevent_active_and_archived_true'),
        ),
    ]
