# Generated by Django 6.0.2 on 2026-02-25 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0002_initial'),
        ('settings', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.operator'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.lead'),
        ),
        migrations.AddField(
            model_name='note',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.operator'),
        ),
        migrations.AddField(
            model_name='situation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.organization'),
        ),
        migrations.AddField(
            model_name='lead',
            name='situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.situation'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', '-created_at'], name='lead_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', 'status'], name='lead_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['center', '-created_at'], name='lead_center_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['center', 'status'], name='lead_center_status_idx'),
        ),
    ]
