# Generated by Django 5.2.11 on 2026-03-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_initial'),
        ('settings', '0004_alter_organization_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='situation',
            constraint=models.CheckConstraint(condition=models.Q(('is_static', True), ('organization__isnull', False), _negated=True), name='situation_static_requires_no_org'),
        ),
    ]
