# Generated by Django 6.0.2 on 2026-02-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='prefer_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
