# Generated by Django 5.2.11 on 2026-04-14 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_initial'),
        ('user', '0002_alter_user_gender_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='days_choice',
            field=models.CharField(blank=True, choices=[('odd_days', 'Toq kunlar'), ('even_days', 'Juft kunlar'), ('every_day', 'Har kuni')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('process', "Bog'langan"), ('canceled', 'Bekor qilingan'), ('sold', 'Sotilgan')], default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='lead',
            name='temperature',
            field=models.CharField(choices=[('hot', 'Issiq'), ('cool', 'Iliq'), ('cold', 'Sovuq')], default='hot', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['lead', 'date'], name='lead_note_lead_date_idx'),
        ),
    ]
