# Generated by Django 5.2.11 on 2026-03-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='days_choice',
            field=models.CharField(blank=True, choices=[('odd days', 'Odd days'), ('even days', 'Even days'), ('every day', 'Every day')], max_length=30, null=True),
        ),
    ]
