# Generated by Django 5.2.11 on 2026-04-14

from django.db import migrations


def fix_lead_choices(apps, schema_editor):
    Lead = apps.get_model("lead", "Lead")
    # 'canseled' → 'canceled'
    Lead.objects.filter(status="canseled").update(status="canceled")
    # 'worm' → 'cold'
    Lead.objects.filter(temperature="worm").update(temperature="cold")


def reverse_fix_lead_choices(apps, schema_editor):
    Lead = apps.get_model("lead", "Lead")
    Lead.objects.filter(status="canceled").update(status="canseled")
    Lead.objects.filter(temperature="cold").update(temperature="worm")


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_alter_lead_days_choice_alter_lead_status_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_lead_choices, reverse_fix_lead_choices),
    ]
