# Generated by Django 5.2.11 on 2026-03-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_alter_lead_days_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='days_choice',
            field=models.CharField(blank=True, choices=[('odd_days', 'Odd days'), ('even_days', 'Even days'), ('every_day', 'Every day')], max_length=30, null=True),
        ),
    ]
