# Generated by Django 6.0.2 on 2026-02-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0004_lead_full_name_lead_phone_number_alter_lead_user"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="lead",
            name="lead_user_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="lead_user_status_idx",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="user",
        ),
    ]

