# Generated by Django 5.2.11 on 2026-03-04 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_group_course_alter_group_lessons_days_choice_and_more'),
        ('lead', '0004_situation_situation_static_requires_no_org'),
        ('settings', '0004_alter_organization_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='group.coursetemplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='lead.source'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('process', 'Process'), ('canseled', 'Canseled')], default='new', max_length=25),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('center__isnull', False), ('is_static', True), _negated=True), name='source_static_requires_no_org'),
        ),
    ]
