# Generated by Django 6.0.2 on 2026-02-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_initial'),
        ('lead', '0004_lead_prefer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, related_name='leads', to='group.day'),
        ),
    ]
