# Generated by Django 6.0.2 on 2026-02-25 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_alter_lead_comment_alter_lead_days'),
        ('settings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.organization'),
        ),
    ]
