# Generated by Django 5.2.11 on 2026-03-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_group_course_alter_group_lessons_days_choice_and_more'),
        ('lead', '0005_alter_lead_course_alter_lead_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='leads', to='group.day'),
        ),
    ]
