# Generated by Django 6.0.2 on 2026-02-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_initial'),
        ('lead', '0005_remove_lead_user'),
        ('settings', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['operator', 'status'], name='lead_operator_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['course'], name='lead_course_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone_number'], name='lead_phone_idx'),
        ),
    ]
