# Generated by Django 6.0.2 on 2026-02-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_alter_situation_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
