# Generated by Django 5.2.11 on 2026-03-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_alter_lead_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('process', 'Process'), ('canseled', 'Canseled'), ('sold', 'Sold')], default='new', max_length=25),
        ),
    ]
