# Generated by Django 6.0.2 on 2026-02-28 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_coursetemplate_teacher'),
        ('lead', '0007_lead_is_active_lead_is_archived'),
        ('settings', '0002_initial'),
        ('user', '0003_alter_operator_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', True), ('is_archived', True), _negated=True), name='prevent_active_and_archived_true'),
        ),
    ]
