# Generated by Django 6.0.2 on 2026-02-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('duration_months', models.PositiveIntegerField(default=1)),
                ('grading_system', models.CharField(choices=[('point', 'Point'), ('percent', 'Percent'), ('ielts', 'IELTS')], default='point', max_length=50)),
                ('color_bg', models.CharField(default='#FFFFFF', help_text='Hex color for course background', max_length=7)),
                ('color_text', models.CharField(default='#000000', help_text='Hex color for course text', max_length=7)),
                ('price_effective_from', models.DateField(blank=True, null=True)),
                ('apply_price_from_month', models.BooleanField(default=False, help_text='If true, apply price change from start of month for related groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('lessons_days_choice', models.CharField(blank=True, choices=[('odd days', 'Odd days'), ('even days', 'Even days')], max_length=30, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('test lesson', 'Test lesson'), ('frozen', 'Frozen')], default='active', max_length=30)),
                ('start_lesson', models.TimeField()),
                ('end_lesson', models.TimeField()),
                ('students_count', models.IntegerField(default=0)),
                ('closed_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
