<<<<<<< HEAD
# Generated by Django 5.2.11 on 2026-03-06 05:55
=======
# Generated by Django 5.2.11 on 2026-03-06 10:25
>>>>>>> 4075a82f507d7f15cd256fe8ac5e659533ce4b80

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('pupil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='pupil.student'),
        ),
    ]
