# Generated by Django 6.0.2 on 2026-02-28 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0002_initial'),
        ('settings', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetemplate',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='assistant_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_group', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='group.coursetemplate'),
        ),
        migrations.AddField(
            model_name='group',
            name='lessons_days',
            field=models.ManyToManyField(blank=True, related_name='groups', to='group.day'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_groups', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='settings.branch'),
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.room'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['status', 'created_at'], name='group_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['teacher', 'status'], name='group_teacher_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('start_lesson__lt', models.F('end_lesson'))), name='group_start_before_end_lesson'),
        ),
    ]
