# Generated by Django 5.2.11 on 2026-03-03 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_initial'),
        ('settings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='settings.branch'),
        ),
    ]
