# Generated by Django 6.0.2 on 2026-02-26 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_initial'),
        ('teacher', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetemplate',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to='teacher.teacher'),
        ),
    ]
