# Generated by Django 5.2.11 on 2026-03-06 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0003_initial'),
        ('pupil', '0001_initial'),
        ('settings', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='assistant_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_group', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='settings.branch'),
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='group.coursetemplate'),
        ),
        migrations.AddField(
            model_name='group',
            name='lessons_days',
            field=models.ManyToManyField(blank=True, related_name='groups', to='group.day'),
        ),
        migrations.AddField(
            model_name='group',
            name='studnets',
            field=models.ManyToManyField(related_name='groups', to='pupil.student'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_groups', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='group.group'),
        ),
        migrations.AddField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='settings.branch'),
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.room'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['group', 'student'], name='attendance_group_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_present', 'date'], name='attendance_ispresent_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'group', 'date')},
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['status', 'created_at'], name='group_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['teacher', 'status'], name='group_teacher_status_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['course', 'branch'], name='group_course_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['branch'], name='group_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['branch', 'status'], name='group_branch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('start_lesson__lt', models.F('end_lesson'))), name='group_start_before_end_lesson'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__lt', models.F('closed_at'))), name='group_start_date_before_end_date'),
        ),
    ]
