# Generated by Django 5.2.11 on 2026-03-24 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0003_initial'),
        ('pupil', '0002_initial'),
        ('settings', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='assistant_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_group', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='settings.branch'),
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='group.coursetemplate'),
        ),
        migrations.AddField(
            model_name='group',
            name='lessons_days',
            field=models.ManyToManyField(blank=True, related_name='groups', to='group.day'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='groups', to='pupil.student'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_groups', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='group.group'),
        ),
        migrations.AddField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='group.group'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='group.group'),
        ),
        migrations.AddField(
            model_name='groupdiscount',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='group.group'),
        ),
        migrations.AddField(
            model_name='groupdiscount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='pupil.student'),
        ),
        migrations.AddField(
            model_name='groupfreeze',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezes', to='group.group'),
        ),
        migrations.AddField(
            model_name='grouphistory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='group.group'),
        ),
        migrations.AddField(
            model_name='groupnote',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='group.group'),
        ),
        migrations.AddField(
            model_name='grouprankingcomment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_comments', to='group.group'),
        ),
        migrations.AddField(
            model_name='grouprankingcomment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_comments', to='pupil.student'),
        ),
        migrations.AddField(
            model_name='groupscore',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='group.group'),
        ),
        migrations.AddField(
            model_name='groupscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='pupil.student'),
        ),
        migrations.AddField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='settings.branch'),
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.room'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['group', 'student'], name='grade_group_student_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['date'], name='grade_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'group', 'date')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['group', 'date'], name='exam_group_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['date'], name='exam_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['group', 'student'], name='attendance_group_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_present', 'date'], name='attendance_ispresent_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'group', 'date')},
        ),
        migrations.AddIndex(
            model_name='groupdiscount',
            index=models.Index(fields=['group', 'created_at'], name='discount_group_date_idx'),
        ),
        migrations.AddIndex(
            model_name='groupdiscount',
            index=models.Index(fields=['student'], name='discount_student_idx'),
        ),
        migrations.AddIndex(
            model_name='groupfreeze',
            index=models.Index(fields=['group', 'start_date'], name='freeze_group_start_idx'),
        ),
        migrations.AddIndex(
            model_name='groupfreeze',
            index=models.Index(fields=['group', 'end_date'], name='freeze_group_end_idx'),
        ),
        migrations.AddIndex(
            model_name='grouphistory',
            index=models.Index(fields=['group', 'created_at'], name='history_group_date_idx'),
        ),
        migrations.AddIndex(
            model_name='grouprankingcomment',
            index=models.Index(fields=['group', 'student'], name='ranking_group_student_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grouprankingcomment',
            unique_together={('group', 'student')},
        ),
        migrations.AddIndex(
            model_name='groupscore',
            index=models.Index(fields=['group', 'student'], name='score_group_student_idx'),
        ),
        migrations.AddIndex(
            model_name='groupscore',
            index=models.Index(fields=['created_at'], name='score_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['status', 'created_at'], name='group_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['teacher', 'status'], name='group_teacher_status_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['course', 'branch'], name='group_course_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['branch'], name='group_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['branch', 'status'], name='group_branch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('start_lesson__lt', models.F('end_lesson'))), name='group_start_before_end_lesson'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__lt', models.F('closed_at'))), name='group_start_date_before_end_date'),
        ),
    ]
