# Generated by Django 5.2.11 on 2026-03-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='students_count',
            new_name='total_student',
        ),
        migrations.RemoveField(
            model_name='coursetemplate',
            name='color_bg',
        ),
        migrations.RemoveField(
            model_name='coursetemplate',
            name='color_text',
        ),
        migrations.AlterField(
            model_name='group',
            name='lessons_days_choice',
            field=models.CharField(blank=True, choices=[('odd days', 'Odd days'), ('even days', 'Even days'), ('every day', 'Every day')], max_length=30, null=True),
        ),
    ]
