# Generated by Django 5.2.11 on 2026-03-04 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_branch'),
        ('settings', '0004_alter_organization_owner'),
        ('teacher', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='group.coursetemplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='lessons_days_choice',
            field=models.CharField(choices=[('odd_days', 'Odd days'), ('even_days', 'Even days'), ('every_day', 'Every day')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['course', 'branch'], name='group_course_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['branch'], name='group_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['branch', 'status'], name='group_branch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__lt', models.F('closed_at'))), name='group_start_date_before_end_date'),
        ),
    ]
