# Generated by Django 5.2.11 on 2026-03-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_rename_students_count_group_total_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='lessons_days_choice',
            field=models.CharField(blank=True, choices=[('odd_days', 'Odd days'), ('even_days', 'Even days'), ('every_day', 'Every day')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('test_lesson', 'Test lesson'), ('frozen', 'Frozen')], default='active', max_length=30),
        ),
    ]
