# Generated by Django 5.2.11 on 2026-03-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_initial'),
        ('pupil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='studnets',
            field=models.ManyToManyField(blank=True, related_name='groups', to='pupil.student'),
        ),
    ]
