# Generated by Django 5.2.11 on 2026-03-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_initial'),
        ('pupil', '0004_rename_studnettransfer_studenttransfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='pupil.student'),
        ),
    ]
