# Generated by Django 5.2.11 on 2026-04-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_attendance_is_present_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_rise',
            field=models.BooleanField(default=False),
        ),
    ]
