# Generated by Django 5.2.11 on 2026-03-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_group_lessons_days_choice_alter_group_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
