# Generated by Django 5.2.11 on 2026-03-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_group_studnets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='studnets',
            new_name='students',
        ),
    ]
