# Generated by Django 5.2.11 on 2026-04-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_group_students'),
        ('group', '0006_attendance_is_rise'),
    ]

    operations = [
    ]
