# Generated by Django 5.2.11 on 2026-04-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_merge_20260407_1703'),
        ('pupil', '0010_merge_20260407_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='groups', to='pupil.student'),
        ),
    ]
