# Generated by Django 5.2.11 on 2026-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_alter_group_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='lessons_days_choice',
            field=models.CharField(choices=[('odd_days', 'Toq kunlar'), ('even_days', 'Juft kunlar'), ('every_day', 'Har kuni')], max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('archived', 'Arxiv'), ('test_lesson', 'Sinov darsi'), ('frozen', "To'xtatilgan")], default='active', max_length=30),
        ),
    ]
