# Generated by Django 5.2.11 on 2026-03-06 10:25

import apps.pupil.models.parent
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('payment_status', models.CharField(choices=[('near payment', 'Near payment'), ('debtor', 'Debtor'), ('no debt', 'No debt'), ('over payment', 'Over payment')], default='no debt', max_length=30)),
                ('comment', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255, validators=[apps.pupil.models.parent.validate_phone_number])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupil.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['payment_status', 'next_payment_date'], name='student_pay_date_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['next_payment_date'], name='student_next_pay_idx'),
        ),
    ]
