# Generated by Django 5.2.11 on 2026-03-24 12:53

import apps.pupil.models.parent
import apps.pupil.models.student
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255, validators=[apps.pupil.models.parent.validate_phone_number])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('payment_status', models.CharField(choices=[('near payment', 'Near payment'), ('debtor', 'Debtor'), ('no debt', 'No debt'), ('over payment', 'Over payment')], default='no debt', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, validators=[apps.pupil.models.student.validate_phone_number])),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('avtive', 'Active'), ('frozen', 'Frozen'), ('archived', 'Archived'), ('lead', 'Lead')], default='avtive', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StudnetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('reason_choice', models.CharField(blank=True, choices=[('far', 'Far')], max_length=30, null=True)),
                ('is_apply_discount', models.BooleanField(default=False)),
                ('is_debt', models.BooleanField(default=False)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('course_end', 'Course_end'), ('specific_month', 'Specific_month')], max_length=30, null=True)),
                ('specific_month', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
