# Generated by Django 6.0.2 on 2026-02-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_coursetemplate_teacher'),
        ('pupil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(related_name='students', to='group.group'),
        ),
    ]
