# Generated by Django 5.2.11 on 2026-03-24 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0004_initial'),
        ('pupil', '0002_initial'),
        ('settings', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupil.student'),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notes', to='user.operator'),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pupil.student'),
        ),
        migrations.AddField(
            model_name='studnettransfer',
            name='from_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_transfers_from', to='settings.branch'),
        ),
        migrations.AddField(
            model_name='studnettransfer',
            name='from_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_transfers_from', to='group.group'),
        ),
        migrations.AddField(
            model_name='studnettransfer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupil.student'),
        ),
        migrations.AddField(
            model_name='studnettransfer',
            name='to_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_transfers_to', to='settings.branch'),
        ),
        migrations.AddField(
            model_name='studnettransfer',
            name='to_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_transfers_to', to='group.group'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['payment_status', 'next_payment_date'], name='student_pay_date_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['next_payment_date'], name='student_next_pay_idx'),
        ),
    ]
