# Generated by Codex on 2026-03-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pupil", "0003_initial"),
    ]

    operations = [
        # Previous attempt to drop non-existent Student.grade caused KeyError in CI.
        # No-op migration kept for sequence consistency.
    ]
