# Generated by Codex on 2026-03-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pupil", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="grade",
        ),
    ]
