# Generated by Django 5.2.11 on 2026-03-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_initial'),
        ('pupil', '0003_initial'),
        ('settings', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudnetTransfer',
            new_name='StudentTransfer',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
    ]