# Generated by Django 5.2.11 on 2026-03-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0004_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='used_coin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
