# Generated by Codex on 2026-03-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_user_field_if_missing(apps, schema_editor):
    """Add student.user column/FK only if it doesn't exist (SQLite-safe)."""
    Student = apps.get_model("pupil", "Student")
    User = apps.get_model("user", "User")

    field = models.OneToOneField(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.SET_NULL,
        related_name="student_profile",
        to=settings.AUTH_USER_MODEL,
    )
    field.set_attributes_from_name("user")

    table = Student._meta.db_table
    column = field.column
    conn = schema_editor.connection

    # check column existence
    exists = False
    with conn.cursor() as cursor:
        if conn.vendor == "sqlite":
            cursor.execute(f"PRAGMA table_info({table});")
            cols = [row[1] for row in cursor.fetchall()]
            exists = column in cols
        else:
            cursor.execute(
                """
                SELECT 1 FROM information_schema.columns
                WHERE table_name = %s AND column_name = %s
                """,
                [table, column],
            )
            exists = cursor.fetchone() is not None

    if not exists:
        schema_editor.add_field(Student, field)

    # ensure FK on postgres if missing
    if conn.vendor == "postgresql":
        fk_exists = False
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT 1
                FROM information_schema.constraint_column_usage ccu
                WHERE ccu.table_name = %s AND ccu.column_name = %s
                """,
                [table, column],
            )
            fk_exists = cursor.fetchone() is not None

        if not fk_exists:
            user_table = User._meta.db_table
            schema_editor.execute(
                f'ALTER TABLE "{table}" '
                f'ADD CONSTRAINT "{table}_{column}_fk" '
                f'FOREIGN KEY ("{column}") REFERENCES "{user_table}" ("id") '
                f'DEFERRABLE INITIALLY DEFERRED;'
            )


class Migration(migrations.Migration):

    dependencies = [
        ("pupil", "0004_remove_student_grade"),
        ("user", "0002_alter_user_role"),
    ]

    operations = [
        migrations.RunPython(add_user_field_if_missing, migrations.RunPython.noop),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
