# Generated by Django 5.2.11 on 2026-04-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0004_rename_studnettransfer_studenttransfer_and_more'),
        ('pupil', '0009_normalize_negative_group_scores'),
    ]

    operations = [
    ]
