# Generated by Django 5.2.11 on 2026-04-07 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_alter_group_students'),
        ('pupil', '0010_merge_20260407_1703'),
        ('settings', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentTransfer',
            new_name='StudnetTransfer',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group'),
        ),
    ]
