# Generated by Django 5.2.11 on 2026-04-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0011_rename_studenttransfer_studnettransfer_student_group'),
        ('pupil', '0011_restore_student_group_fk'),
    ]

    operations = [
    ]
