# Generated by Django 5.2.11 on 2026-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0013_fix_studenttransfer_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_status',
            field=models.CharField(choices=[('near payment', "To'lov yaqin"), ('debtor', 'Qarzdor'), ('no debt', "To'langan"), ('over payment', "Ortiqcha to'lov")], default='no debt', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('frozen', "To'xtatilgan"), ('archived', 'Arxiv'), ('lead', 'Lid')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='studenttransfer',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('course_end', 'Kurs oxiri'), ('specific_month', 'Aniq oy')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studenttransfer',
            name='reason_choice',
            field=models.CharField(blank=True, choices=[('far', 'Uzoq')], max_length=30, null=True),
        ),
    ]
