# Generated by Django 5.2.11 on 2026-04-14

from django.db import migrations


def fix_student_status_avtive(apps, schema_editor):
    Student = apps.get_model("pupil", "Student")
    Student.objects.filter(status="avtive").update(status="active")


def reverse_fix_student_status(apps, schema_editor):
    Student = apps.get_model("pupil", "Student")
    Student.objects.filter(status="active").update(status="avtive")


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0014_alter_student_payment_status_alter_student_status_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_student_status_avtive, reverse_fix_student_status),
    ]
