# Generated by Django 5.2.11 on 2026-02-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=1024)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longtitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('sms_identifier', models.CharField(blank=True, help_text='Short name used when sending SMS from this branch', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_accounts', models.JSONField(blank=True, help_text='Optional bank account details JSON', null=True)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('terminal_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_consolidation', models.CharField(choices=[('manual', 'Manual'), ('once a day', 'Once A Day'), ('auto', 'Auto')], default='manual', max_length=20)),
                ('organization_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization/logos/')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longtitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=1024)),
                ('sms_identifier', models.CharField(blank=True, help_text='Short name used when sending SMS from this branch', max_length=128)),
                ('bank_accounts', models.JSONField(blank=True, help_text='Optional bank account details JSON', null=True)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('terminal_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('top_text', models.TextField(blank=True, help_text='Text shown in the top part of receipt (address/phone)')),
                ('footer_text', models.TextField(blank=True, help_text='Footer / thank you / social links')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='receipts/logos/')),
                ('show_logo', models.BooleanField(default=True)),
                ('show_top_section', models.BooleanField(default=True)),
                ('show_address', models.BooleanField(default=True)),
                ('show_phone', models.BooleanField(default=True)),
                ('show_print_time', models.BooleanField(default=True)),
                ('show_payment_id', models.BooleanField(default=True)),
                ('show_student_info', models.BooleanField(default=True)),
                ('show_group_info', models.BooleanField(default=True)),
                ('show_payment_form', models.BooleanField(default=True)),
                ('show_payment_date', models.BooleanField(default=True)),
                ('show_cashier', models.BooleanField(default=True)),
                ('show_amount', models.BooleanField(default=True)),
                ('show_footer', models.BooleanField(default=True)),
                ('show_qr_code', models.BooleanField(default=True)),
                ('show_teacher_name', models.BooleanField(default=False)),
                ('show_course_price', models.BooleanField(default=False)),
                ('logo_position', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='top', max_length=10)),
            ],
            options={
                'verbose_name': 'Receipt Settings',
                'verbose_name_plural': 'Receipt Settings',
            },
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True)),
            ],
        ),
    ]
