# Generated by Django 5.2.11 on 2026-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Filial', 'verbose_name_plural': 'Filiallar'},
        ),
        migrations.AddConstraint(
            model_name='receiptsettings',
            constraint=models.CheckConstraint(condition=models.Q(('branch__isnull', False), ('organization__isnull', False), _connector='OR'), name='receipt_settings_branch_or_org'),
        ),
    ]
