# Generated by Django 5.2.11 on 2026-03-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_organization_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
