# Generated by Django 6.0.2 on 2026-02-25 11:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='teacher-avatar')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('kpi', models.IntegerField(blank=True, null=True)),
                ('monthly_per_lesson', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('monthly_per_student', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('percentage_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('lesson_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('per_student_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='settings.branch')),
                ('specialty', models.ManyToManyField(blank=True, related_name='teachers', to='teacher.specialty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
