# Generated by Django 6.0.2 on 2026-02-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='teacher-avatar')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('kpi', models.IntegerField(blank=True, null=True)),
                ('monthly_per_lesson', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('monthly_per_student', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('specialty', models.ManyToManyField(related_name='teachers', to='teacher.specialty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
